# flowc/codegen.py
import os
from typing import List

HEADER = (
    "# Auto-generated by flowc transpiler\n"
    "import subprocess, sys\n\n"
)

RUN_FN = (
    "def run_cmd(cmd, timeout=None):\n"
    "    print(f\"[run] {cmd}\")\n"
    "    try:\n"
    "        subprocess.run(cmd, shell=True, timeout=timeout, check=True)\n"
    "        return True\n"
    "    except subprocess.TimeoutExpired:\n"
    "        print('Timeout', file=sys.stderr)\n"
    "        return False\n"
    "    except subprocess.CalledProcessError as e:\n"
    "        print('Command failed:', e, file=sys.stderr)\n"
    "        return False\n\n"
)

def transpile(ir: List[dict], out_path: str):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    with open(out_path, "w") as f:
        f.write(HEADER)
        f.write(RUN_FN)

        # Step functions
        for instr in ir:
            if instr.get("op") != "RUN":
                continue

            name = instr["step"]
